# -*- coding: utf-8 -*-
"""Task1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BTiLje0Cq2Zm4qnPpJqv_9nhu9xD-HUI
"""

import pandas as pd
import matplotlib.pyplot as plt

#Read the dataset
data=pd.read_csv("/content/Metadata_Country_API_SP.POP.TOTL_DS2_en_csv_v2_5695140.csv")

#Plotting the bar chart for categorical variable
gender_counts = data['Region']. value_counts()

bar_width=0.8
x=range(len(gender_counts.index))

plt.bar(gender_counts.index , gender_counts.values)
plt.xlabel('Region')
plt.ylabel('Count')
plt.title('Region Distribution')

plt.xticks(x, gender_counts.index,rotation=45)

for i,count in enumerate(gender_counts.values):
  plt.text(i,count,str(count),ha='center', va='bottom')

plt.tight_layout()
plt.show()